### PR TITLE
Fix #172: Fix accepting `:` as command name separator, offer using it by default

### LINKED ISSUE #172: Shortcuts do not work
With `:` separator you can run command `doctrine:migrations:diff` by `d:mi:di`. 
This do not work for `/` separator. E.g. `debug/reset` can't be executed by `d/r`

### PR DESCRIPTION
**Pull request by samdark**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #172

### CODE REVIEW

File: src/Application.php [hunk 1]
```diff
@@ -91,9 +89,7 @@ public function addOptions(InputOption $options): void
 
     public function extractNamespace(string $name, int $limit = null): string
     {
-        $parts = explode('/', $name, -1);
-
-        return implode('/', null === $limit ? $parts : array_slice($parts, 0, $limit));
+        return parent::extractNamespace(str_replace('/', ':', $name), $limit);
     }
 
     public function getNamespaces(): array
```
Comment (vjik) [inline src/Application.php:95]: Here need to take into account that both `:` and `/`  can be used as a separator.

**Review by vjik — CHANGES_REQUESTED** [review]
